spring:
  application:
    name: apicomp
  datasource:
    url: 'jdbc:h2:file:./.db/apicomp.db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE'
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
testRunner:
  database: false
